// Case-study data, ported from the Claude Design v2 mockup
// (ClaudeDesign_project/Yoonji Nam Portfolio v2.dc.html -> works()).
// Consumed by case-overlay.js.
const WORKS = [
  {
    t: "PBV Passenger Infotainment System",
    cat: "Digital Product",
    y: "2023—2026",
    co: "Maba Industry",
    role: "Lead UX/UI Designer",
    ty: "In-cabin infotainment",
    sum: "Passenger-facing infotainment for a purpose-built vehicle cabin, carried from ride scenario to a real vehicle driving through Gangnam.",
    tags: ["Mobility", "Infotainment", "Multi-Display", "UX Writing"],
    facts: [
      { k: "Background", v: "A ₩8B national R&D program building a purpose-built vehicle cabin around three 55-inch in-cabin displays." },
      { k: "Problem", v: "Passengers have no habit for a cabin that shows them things, and three large screens compete for the same attention." },
      { k: "Approach", v: "Wrote the ride as a scenario first, gave each display a single job, and defined the language the vehicle uses to speak to the people inside it." },
      { k: "Outcome", v: "Demonstrated in a real vehicle on a Gangnam route. Innovation IT Award." },
    ],
    metrics: [
      { n: "3", c: "55-inch displays" },
      { n: "₩8B", c: "R&D program" },
      { n: "Award", c: "Innovation IT" },
    ],
    secs: [
      { l: "Scenario", h: "The ride is the interface, not the screen.", b: "I mapped the ride as a sequence — boarding, moving, arriving — and asked what a passenger needs to know at each moment. Most of the answers were smaller than a screen full of content.", b2: "That sequence became the spec the three displays were designed against, instead of each screen being designed on its own." },
      { l: "Structure", h: "One job per display.", b: "The center display carries the ride itself: where we are and what happens next. The side displays carry content that can be ignored without cost.", b2: "Separating the roles removed the competition between screens and let the cabin stay quiet while the vehicle is moving." },
      { l: "Engineering", h: "What a screen can honestly promise.", b: "Reading CAN data meant every status the interface showed had to be something the vehicle could actually report, at a rate a passenger can trust.", b2: "Where the data was uncertain, the copy changed rather than the promise — writing became part of the interface work." },
    ],
  },
  {
    t: "PBV Content Management System",
    cat: "Digital Product",
    y: "2025—2026",
    co: "Maba Industry",
    role: "UX/UI Designer",
    ty: "Operator admin tool",
    sum: "The operator tool behind the cabin displays: scheduling, content structure, and a component set shared with the vehicle UI.",
    tags: ["Admin Tool", "Information Architecture", "Design System"],
    facts: [
      { k: "Background", v: "Everything a passenger sees in the cabin is scheduled by an operator in a back-office tool." },
      { k: "Problem", v: "Content types, display roles, and schedules had grown separately, so the tool did not match the way the cabin behaves." },
      { k: "Approach", v: "Rebuilt the information architecture around display roles, then unified list, schedule, and preview into one reusable pattern." },
      { k: "Outcome", v: "A single content pattern that absorbs new content types without new screens." },
    ],
    metrics: [],
    secs: [
      { l: "Architecture", h: "Operator tooling is part of the passenger experience.", b: "If the tool is confusing, the cabin becomes confusing one step later. I mapped content types directly onto the three display roles so the two models stay in sync.", b2: "Operators stopped having to translate between what they schedule and what the passenger will see." },
      { l: "System", h: "One pattern, reused.", b: "List, scheduling, and preview share a single layout and component set, so adding a content type is a configuration rather than a redesign.", b2: "The components defined here became the reference set for the vehicle-side interface as well." },
    ],
  },
  {
    t: "Driver & Passenger Control Pad",
    cat: "Digital Product",
    y: "2024—2025",
    co: "Maba Industry",
    role: "UX/UI Designer",
    ty: "In-car control app",
    sum: "Two control apps for one cabin — separating what the driver commands from what passengers can adjust.",
    tags: ["Mobility", "In-Car App", "Control UI"],
    facts: [
      { k: "Background", v: "The PBV cabin is controlled from pads on both the driver side and the passenger side." },
      { k: "Problem", v: "Driver and passengers need the same cabin but not the same authority over it." },
      { k: "Approach", v: "Split controls by authority and by frequency, then tuned targets and feedback for a vehicle in motion." },
      { k: "Outcome", v: "A control layer that never shows a state the vehicle cannot confirm." },
    ],
    metrics: [],
    secs: [
      { l: "Authority", h: "Two people, one cabin, different controls.", b: "The driver pad holds operational commands; the passenger pad holds comfort and content. Anything that affects the ride itself stays on one side only.", b2: "Frequency decided placement: what people touch while moving stays reachable without looking for it." },
      { l: "Detail", h: "Designed for hands in a moving vehicle.", b: "Touch targets, feedback timing, and state clarity were set for motion, not for a phone resting on a desk.", b2: "Each control was checked against what the vehicle reports back, so a pressed button never claims more than the hardware has done." },
    ],
  },
  {
    t: "Samsung Tech Fair Docent App",
    cat: "Digital Product",
    y: "2022",
    co: "Cheil Worldwide",
    role: "UX/UI Designer (Freelance)",
    ty: "Event mobile app",
    sum: "A docent app for Samsung Tech Fair visitors, with the voting flow rebuilt to survive the end of a long show day.",
    tags: ["Mobile App", "Event Service", "UX Writing"],
    facts: [
      { k: "Background", v: "Visitors used the app to navigate the fair, follow exhibit explanations, and vote for projects." },
      { k: "Problem", v: "Voting sat at the end of the visit, when attention was lowest, and the flow asked for more than visitors had left." },
      { k: "Approach", v: "Shortened the flow, rewrote the labels in the visitor's words, and made the current step visible at all times." },
      { k: "Outcome", v: "Visitor satisfaction rose 18pp to 98%." },
    ],
    metrics: [
      { n: "98%", c: "Visitor satisfaction" },
      { n: "+18pp", c: "Change vs. previous year" },
    ],
    secs: [
      { l: "Problem", h: "Voting was the last step and the first thing people dropped.", b: "By the time visitors reached voting they had already walked the whole floor. Anything that required rereading lost them.", b2: "The failure was not the feature but its position in the day." },
      { l: "Rewrite", h: "Fewer steps, plainer words.", b: "I cut the flow to the minimum number of decisions and rewrote every label so it could be understood at a glance while standing.", b2: "Progress was made visible so visitors always knew how much was left before committing." },
    ],
  },
  {
    t: "Public Parking Payment Kiosk",
    cat: "Digital Product",
    y: "2021",
    co: "Seoul Facilities Corporation",
    role: "Design Intern",
    ty: "Public kiosk UI",
    sum: "A universal-design payment interface for Seoul's public parking kiosks, based on a citywide audit and on-site observation.",
    tags: ["Kiosk", "Public Service", "Universal Design"],
    facts: [
      { k: "Background", v: "Seoul Facilities Corporation operates public parking payment kiosks across the city." },
      { k: "Problem", v: "Screens differed from site to site, and the people who struggled most had no alternative way to pay." },
      { k: "Approach", v: "Audited 37 kiosks, observed five sites in person, and prototyped one consistent universal-design flow." },
      { k: "Outcome", v: "Proposal and working prototype delivered. Outstanding Intern Award." },
    ],
    metrics: [
      { n: "37", c: "Kiosks audited" },
      { n: "5", c: "Sites observed" },
      { n: "Award", c: "Outstanding Intern" },
    ],
    secs: [
      { l: "Field", h: "The pain points that matter were not in the spec.", b: "Standing at the machines showed what a screenshot cannot: glare, height, queue pressure, and people who could not read the labels quickly enough.", b2: "Watching users who had no choice but to finish still sets how I think about accessibility." },
      { l: "Proposal", h: "One flow, larger targets, plain language.", b: "I unified the payment sequence across kiosk types and rewrote each step into a single question with a single decision.", b2: "The prototype let the team test the flow before committing hardware, which is where public-service design usually gets stuck." },
    ],
  },
  {
    t: "K-Display 2024",
    cat: "Experience Design",
    y: "2024",
    co: "Maba Industry",
    role: "Experience Designer",
    ty: "Exhibition",
    sum: "A booth that let visitors experience a PBV cabin they could not ride, compressed into a few minutes.",
    tags: ["Exhibition", "Immersive Experience", "PBV"],
    facts: [
      { k: "Background", v: "K-Display is Korea's display industry exhibition, where the PBV cabin concept was shown publicly." },
      { k: "Problem", v: "A cabin experience only makes sense while moving, and a show floor does not move." },
      { k: "Approach", v: "Rebuilt the ride as a staged sequence so the displays told the story in the order a passenger would meet it." },
      { k: "Outcome", v: "Visitors could follow the cabin concept without a guide." },
    ],
    metrics: [],
    secs: [
      { l: "Translation", h: "A ride, staged for a floor.", b: "The booth borrowed the ride scenario: arrive, settle, look around, leave. Each stage exposed one part of the cabin rather than all of it at once.", b2: "What the vehicle would have explained through motion, the booth explained through sequence." },
      { l: "Content", h: "Screens that explain themselves in a minute.", b: "Visitors give an unfamiliar technology about a minute. Every screen was written to land in that first minute or not at all.", b2: "Detail was moved to the moments where a visitor had already chosen to stay." },
    ],
  },
  {
    t: "World Smart City Expo 2025",
    cat: "Experience Design",
    y: "2025",
    co: "Maba Industry",
    role: "Experience Designer",
    ty: "Exhibition",
    sum: "The mobility zone of the LH exhibit, placing the PBV cabin inside a wider smart-city story.",
    tags: ["Exhibition", "Mobility Zone", "LH"],
    facts: [
      { k: "Background", v: "A mobility zone within LH's exhibit at World Smart City Expo 2025." },
      { k: "Problem", v: "Mobility had to read as one part of a city, not as a standalone product demo." },
      { k: "Approach", v: "Connected the cabin experience to the surrounding city narrative so visitors moved through it as a continuous story." },
      { k: "Outcome", v: "A zone that visitors could enter at any point and still follow." },
    ],
    metrics: [],
    secs: [
      { l: "Context", h: "The vehicle is a room in a larger city.", b: "Instead of opening with the vehicle, the zone opened with the movement problem the city has, and let the cabin arrive as the answer.", b2: "That framing let visitors who had no interest in mobility still understand why the cabin exists." },
      { l: "Flow", h: "Designed for people who enter in the middle.", b: "Exhibition visitors rarely start at the start. Each station was written to stand alone while still adding to the sequence.", b2: "Entry points were repeated so the story restarts wherever a visitor happens to arrive." },
    ],
  },
  {
    t: "CES 2023 — Samsung Ready Care",
    cat: "Experience Design",
    y: "2023",
    co: "Cheil Worldwide",
    role: "UX/UI Designer (Freelance)",
    ty: "Global tech show",
    sum: "Content UI and on-site operation for Samsung's Ready Care exhibit at CES 2023.",
    tags: ["Global Tech Show", "Content UI", "Operation"],
    facts: [
      { k: "Background", v: "Ready Care was shown to an international CES audience across language and context differences." },
      { k: "Problem", v: "A health-and-care concept has to be understood without a shared cultural reference or a long explanation." },
      { k: "Approach", v: "Designed the content UI around a single demonstrable moment and supported it during the show." },
      { k: "Outcome", v: "Ran through the full show week with on-site operation." },
    ],
    metrics: [],
    secs: [
      { l: "Clarity", h: "One idea, understood without language.", b: "CES audiences pass by. The exhibit had to make its point through what was shown on screen rather than what was said next to it.", b2: "Copy was reduced until the demonstration carried the meaning by itself." },
      { l: "Operation", h: "Designing while the show is running.", b: "Being on site meant watching real visitors miss things and adjusting content between sessions.", b2: "Show floors are the fastest usability test I have worked with." },
    ],
  },
  {
    t: "CES 2023 — HD Hyundai OceanWise",
    cat: "Experience Design",
    y: "2023",
    co: "Cheil Worldwide",
    role: "Project Manager",
    ty: "Global tech show",
    sum: "Project management and film content for HD Hyundai's OceanWise exhibit at CES 2023.",
    tags: ["Global Tech Show", "PM", "Film Content"],
    facts: [
      { k: "Background", v: "HD Hyundai presented its ocean transformation vision through large-format film content." },
      { k: "Problem", v: "A vision this abstract depends entirely on pacing and sequence to be felt rather than explained." },
      { k: "Approach", v: "Managed the content schedule and production alongside the design and film teams." },
      { k: "Outcome", v: "Delivered on the CES timeline across distributed teams." },
    ],
    metrics: [],
    secs: [
      { l: "Role", h: "Managing the work, not only the screens.", b: "This project taught me the part of design that happens between teams: scope, sequence, and who decides what by when.", b2: "Knowing how production actually runs changed how I hand off design work now." },
      { l: "Content", h: "Vision reads through pacing.", b: "The film had to move from problem to future without a narrator carrying the burden.", b2: "Editing decisions were the experience decisions." },
    ],
  },
  {
    t: "Quote Bakery — Daily Quote Service",
    cat: "Side Projects",
    y: "2023",
    co: "Self-initiated",
    role: "Product Designer",
    ty: "Launched service",
    sum: "A daily quote service designed and launched with a side-project team, from concept to a live product.",
    tags: ["Service Launch", "Product Design", "DDD"],
    facts: [
      { k: "Background", v: "Built with a cross-functional side-project team through DDD." },
      { k: "Problem", v: "Daily content services are easy to start and hard to make worth returning to." },
      { k: "Approach", v: "Designed the smallest daily loop worth keeping, then shipped it rather than expanding the scope." },
      { k: "Outcome", v: "Launched as a working service." },
    ],
    metrics: [],
    secs: [
      { l: "Scope", h: "Ship the loop, not the roadmap.", b: "The team cut everything that did not serve one daily moment. What remained was small enough to actually launch.", b2: "Working with developers from day one changed which ideas survived." },
      { l: "Craft", h: "A product with no company behind it.", b: "Without a brand system to inherit, every decision — tone, type, rhythm — had to be argued from the product itself.", b2: "It is the clearest picture of what I design when nothing is given to me." },
    ],
  },
  {
    t: "Hyundai Mobis ESG Ideathon",
    cat: "Side Projects",
    y: "2023",
    co: "Self-initiated",
    role: "Designer",
    ty: "Idea-thon",
    sum: "A traffic-safety concept for senior drivers, developed for the Hyundai Mobis ESG Ideathon.",
    tags: ["Idea-thon", "Senior Driver", "Traffic Safety"],
    facts: [
      { k: "Background", v: "An ESG idea competition hosted by Hyundai Mobis." },
      { k: "Problem", v: "Senior drivers face rising risk, and most proposed solutions ask them to give something up." },
      { k: "Approach", v: "Framed the concept around keeping mobility rather than restricting it." },
      { k: "Outcome", v: "Concept and proposal delivered within the competition format." },
    ],
    metrics: [],
    secs: [
      { l: "Framing", h: "Safety that does not take mobility away.", b: "Restriction is the obvious answer and the one most likely to be ignored. The concept looked instead at what support would be accepted voluntarily.", b2: "Designing for a group I am not part of meant starting from their reasons, not their risks." },
      { l: "Format", h: "Two days to make an idea legible.", b: "Competition formats reward clarity over completeness — a concept has to be understood before it can be judged.", b2: "The constraint is good practice for any first pitch of a product idea." },
    ],
  },
  {
    t: "HCI College Membership, Cohort 2",
    cat: "Side Projects",
    y: "2023—2024",
    co: "Companoid Institute of Technology",
    role: "Researcher",
    ty: "Research program",
    sum: "A research cohort at Companoid Institute of Technology, ending in a paper published through the HCI Society of Korea.",
    tags: ["Research", "HCI", "Academic Paper"],
    facts: [
      { k: "Background", v: "A selective HCI research membership program, Cohort 2." },
      { k: "Problem", v: "Practice-side design habits and research-side rigor rarely meet in the same project." },
      { k: "Approach", v: "Ran a study end to end, from question to method to written argument." },
      { k: "Outcome", v: "Paper published through the HCI Society of Korea." },
    ],
    metrics: [],
    secs: [
      { l: "Method", h: "Writing forces the argument to be real.", b: "A paper does not accept a claim without evidence, which is a useful discipline to bring back into product work.", b2: "It changed how I separate what I observed from what I concluded." },
      { l: "Transfer", h: "Research that survives contact with shipping.", b: "Most of what I learned here shows up in how I structure early-stage questions rather than in formal studies.", b2: "Knowing the rigorous version makes the fast version honest about what it skipped." },
    ],
  },
];
